/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "seyugcsyzkiuzpdlnxvx";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleXVnY3N5emtpdXpwZGxueHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDQxMjYsImV4cCI6MjA2OTYyMDEyNn0.YQonMOa0p1Z_rWcWieobt3EMVDRK_1EE5SD2Lel8tSs";